tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-container": "#0a5867",
        "on-background": "#2b3436",
        "error-dim": "#67040d",
        "secondary-dim": "#3a5761",
        "surface-dim": "#d3dcde",
        "surface-container": "#e9eff1",
        "on-primary": "#effbff",
        "tertiary-fixed-dim": "#aec8ef",
        "secondary-fixed-dim": "#badae4",
        "on-tertiary-fixed-variant": "#3a5475",
        "on-secondary-fixed-variant": "#436069",
        "secondary": "#46636d",
        "on-surface-variant": "#586163",
        "surface": "#f7fafb",
        "on-secondary": "#f0fbff",
        "on-primary-fixed-variant": "#1b6271",
        "surface-container-low": "#eff4f6",
        "on-tertiary-container": "#304a6b",
        "tertiary": "#476083",
        "surface-tint": "#236777",
        "surface-bright": "#f7fafb",
        "primary": "#236777",
        "outline": "#737c7f",
        "surface-container-highest": "#dbe4e6",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e2e9eb",
        "on-error": "#fff7f6",
        "secondary-fixed": "#c8e8f3",
        "tertiary-container": "#bcd6fe",
        "primary-dim": "#105b6a",
        "on-tertiary-fixed": "#1c3757",
        "tertiary-dim": "#3b5476",
        "on-secondary-container": "#39565f",
        "primary-container": "#aaeafc",
        "inverse-primary": "#aaeafc",
        "on-surface": "#2b3436",
        "background": "#f7fafb",
        "on-tertiary": "#f8f8ff",
        "tertiary-fixed": "#bcd6fe",
        "primary-fixed-dim": "#9cdbed",
        "error": "#a83836",
        "outline-variant": "#aab3b6",
        "on-primary-fixed": "#004451",
        "surface-variant": "#dbe4e6",
        "inverse-on-surface": "#9a9d9f",
        "primary-fixed": "#aaeafc",
        "on-error-container": "#6e0a12",
        "secondary-container": "#c8e8f3",
        "error-container": "#fa746f",
        "inverse-surface": "#0b0f10",
        "on-secondary-fixed": "#26434c"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
}
